# Generated by Django 2.0.3 on 2018-10-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0008_auto_20180903_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfluenceInfo',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('field', models.CharField(blank=True, max_length=255, null=True)),
                ('influ', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'influence_info',
                'managed': False,
            },
        ),
    ]
